---
ansible_connection: winrm
ansible_psrp_auth: basic
ansible_psrp_protocol: http
ansible_psrp_message_encription: never
ansible_winrm_server_cert_validation: ignore
ansible_user: alan
ansible_password: 1234qwer.
