vm:
  children:
    linux:
      hosts:
        192.168.15.16      

    windows:
      hosts:
        192.168.15.17        
       
connectorlinux:
  children:
    linux:

connectorwindows:
  children:
    windows:

